---
title: "Continuous Random Variables"
author: 
- "Mine Dogucu"
- "Noah Johnson"
date: "April 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Definition

A continuous random variable Y has a sample space $\Omega_Y$ that is uncountably infinite.

### Examples

+ Let Y be survival times after cancer treatment. Then $\Omega_Y = [0, \infty)$

+ Let Y be the proportion of individuals in an infinite population with a particular genetic marker. Then $\Omega_Y = [0,1]$

### Probability Density Function

A probability density function (pdf) is a function that gives the relative likelihood (not probability) that a variable takes on a value within its sample space.

### Properties

1. $f(y | \theta) \geq 0$ $\forall y \in \Omega_Y$

2. $\int_{y \in \Omega_Y} f(y | \theta) dy = 1$

3. $p(y \in B) = \int_{y \in B} f(y | \theta) dy$  $\forall B \subset \Omega_Y$

Note: Probability is represented as area under the density function.

Example: Let Y be a continuous random variable describing, say, hour of death during the day. What is $P(Y = 13.47)$, where $\Omega_Y = [0,24]$?

## Uniform Distribution

### Definition

The variable Y follows a uniform distribution with parameters $\theta = {a,b}$, $Y ~ U(a,b)$ where $a<b$, if $f_y(y | a,b) = \frac{1}{b-a} I(y \in [a,b])$

### Example

Let Y be the hour of death during the day. Then $Y ~ U[0,24)$

### Properties

1. $f_y(y|0,24) = \frac{1}{24} I(y \in [0,24]) \geq 0$ $\forall y \in \Omega_y$

2. $\int_0^{24} \frac{1}{24}dy = \frac{24- 0}{24} = 1$

3. E.g. $P(Y < 12) = \int_0^{12}\frac{1}{24} = 0.5$

## Exponential Distribution

Suppose Y = time for a lightbulb to burn out.

$\Omega = [0,\infty)$ $f_Y(y|\lambda) = \lambda exp(-\lambda y ) I(y \geq 0)$

What is the probability that a lightbulb burns out between 100 and 200 days after it is installed.

$$
\int_{100}^{200} \lambda e^{-\lambda y} dy = -e^{-\lambda y} \rvert_{100}^{200} \\
= -e^{-200\lambda} + e^{-100\lambda}
$$

## Expected Value

$E(y|\theta) = \int_{y \in \Omega_Y} y f(y | \theta) dy$

For the exponential distribution,

$E(y | \theta) = \int_0^\infty y \lambda e^{-\lambda y} dy$

Let $u = \lambda y$, then $\frac{du}{dy} = \lambda \implies \frac{du}{\lambda} = dy$

so $E(y | \theta) = \frac{1}{\lambda} \int_0^\infty u e^{-u} du = \frac{1}{\lambda}$ (integration by parts, not gonna put that here)

## Variance

$Var(y | \theta) = E((Y - E(Y|\theta))^2|\theta) = E(Y^2|\theta) - E(Y|\theta)^2$

For the exponential distribution,

$Var(y | \lambda) = \frac{1}{\lambda^2}$
